services:
  phobos-util:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: phobos-util
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

networks:
  default:
    external: true
    name: proxy